### PR TITLE
Tested HW support for 72-2540, add pytest tests

### PR DESCRIPTION
**Pull request by thomas-phillips-nz**
I tried to split everything into separate commits, can remove individual commits if you don't want to include them (e.g. removing trailing whitespace)

Tested everything in the new pytest file
- Version
- Voltage setting/reading
- Current setting/reading
- Memory store/recall all 5 slots
- Beep on/off
- Output on/off
- Running current/voltage

### CODE REVIEW

**Comment by kxtells** [comment]
HI @thomas-phillips-nz , everything looks good and clean. Thanks for your effort :-)

I would suggest adding some small documentation at least in the README to explain about the tests and the two environment variables governing them before we merge this PR.

**Comment by thomas-phillips-nz** [comment]
Sure, will do when I get into the office tomorrow.

Should I add pytest to requirements.txt? It's not really required for running, only development/testing.

**Comment by kxtells** [comment]
For the moment I think we do not need to add `pytest` in requirements.txt.

We could add it as `extras` but let's keep it simple for now and do nothing about it :-p

**Comment by thomas-phillips-nz** [comment]
Have added changes to the readme now, and improved the test a little bit around finding the COM port.

**Comment by kxtells** [comment]
Looks good and clean, merging.

**Pull request merged**
