### PR TITLE
Add packaging, tests and pep8 fixes

### PR DESCRIPTION
**Pull request by yhvh**
If you want me to clean this up (setup.cfg/undelete gtk thing) let me know and I will do.
I just add as prompt for you to package this since we had to do for our work.

I deleted the gui file because we don't need it and it contained too many pep8 wrongs to bother fixing.

Again, not meant to be merged without work, any errors in setup.cfg are due to copy/paste from our internal files.

We do not distribute this package in work, it is for internal hardware integration tests.

### CODE REVIEW

**Comment by yhvh** [comment]
Another thing which might be done is add the script as an entry_point. This is installed into the correct path for availability on the system.

**Comment by kxtells** [comment]
Thanks for the packaging!

The additions look mostly fine to me. The pep8 fixes too (except things like the [assignment alignment ](https://github.com/kxtells/tenma-serial/pull/6/commits/3edde902ab39b1f5b5e837cbf1ec06c80fee24bd#diff-7a3da0c7a776865f547cca79175063c6L99) which I believe actually goes against pep8).

What I'm not fond of is the tox and bitbucket-pipelines related files. Those are very specific files from specific systems and I'd rather not go there.

And of course, gtkIndicator should not be removed (even if the PEP8 wrongs are not fixed right now).

So yeah, from my point of view, remove the tox and bitbucket related files, recover the gtkIndicator and I'll happily merge this. Probably the setup.cfg needs some work, but I've tested locally and it's a good start.

**Comment by yhvh** [comment]
Added entry_points (also a main function in tenmaControl.py to wrap script).
Resurrected gtkIndicator.py and did pep8 fixes.
Use pkg_resources in gtkIndicator.py for logo.png.
Deleted tox.ini and bitbucket-pipeline.

**Comment by yhvh** [comment]
Done. Thanks for your patience.

**Pull request merged**
